name: Docker Deploy CI

on:
  push:
    branches: [main]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
        name: Check out code

      - uses: Saionaro/extract-package-version@v1.2.1
        name: Extract version
        id: extract_version

      - uses: mr-smithers-excellent/docker-build-push@v6.2
        name: Build & Push Docker Image
        with:
          image: deepacks/party-playlists
          tags: ${{ steps.extract_version.outputs.version }}, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildArgs: SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} --build-arg COOKIE_SECRET=${{secrets.COOKIE_SECRET}}

  update-service:
    runs-on: ubuntu-latest
    needs: [build-image]

    steps:
      - uses: actions/checkout@v4.1.1
        name: Check out code

      - uses: Saionaro/extract-package-version@v1.2.1
        name: Extract version
        id: extract_version

      - name: ssh update service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            docker image pull deepacks/party-playlists:${{ steps.extract_version.outputs.version }}
            docker service update --image deepacks/party-playlists:${{ steps.extract_version.outputs.version }} party-playlists_fe
            docker container prune -f && docker image prune -f
